# Generated by Django 5.0.6 on 2024-06-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='body',
        ),
    ]
