# Generated by Django 5.0.6 on 2024-06-20 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_deposittransaction_user'),
        ('users', '0003_alter_userlibraryaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowing', to='users.userlibraryaccount'),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='users.userlibraryaccount'),
        ),
    ]
