# Generated by Django 5.0.6 on 2024-06-20 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_borrowingtransaction_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowing_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
