# Generated by Django 5.0.6 on 2024-06-20 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_borrowingtransaction_user_and_more'),
        ('users', '0007_alter_userlibraryaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userlibraryaccount'),
        ),
    ]
